const INITIAL_LAYOUT = {
  "title": "金讚廠房工程平面配置圖 (Chin Chun Layout)",
  "drawing_number": "CC-ENG-2026-001",
  "author": "Derek Yeh",
  "version": "V1.3",
  "date": "2026/08/05",
  "grid": {
    "bay_size": 5.0,
    "cols_x": 21,
    "cols_y": 9,
    "col_size": 0.5,
    "origin_x": 0.0,
    "origin_y": 0.0
  },
  "equipment": [
    {
      "id": "eq_dc_n1_1",
      "code": "N1-1",
      "name": "DC (集塵設備/DC)",
      "zone": "ADH 1",
      "x": 3.5,
      "y": 2.0,
      "width": 3.2,
      "height": 3.8,
      "color": "#4A90E2",
      "category": "ADH",
      "floor": "1F"
    },
    {
      "id": "eq_vcut2_j1_1",
      "code": "J1-1",
      "name": "V Cut 2 (V型裁斷機)",
      "zone": "ADH 1",
      "x": 9.5,
      "y": 1.2,
      "width": 4.5,
      "height": 4.6,
      "color": "#F5A623",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_tcut2",
      "code": "T Cut 2",
      "name": "T Cut 2 (裁切機 2)",
      "zone": "ADH 1",
      "x": 18.2,
      "y": 1.2,
      "width": 4.5,
      "height": 2.7,
      "color": "#F5A623",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_tcut1",
      "code": "T Cut 1",
      "name": "T Cut 1 (裁切機 1)",
      "zone": "ADH 1",
      "x": 18.2,
      "y": 4.3,
      "width": 4.5,
      "height": 2.7,
      "color": "#F5A623",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_adh1_m1_1",
      "code": "M1-1",
      "name": "ADH 1 (貼合機主機 M1-1)",
      "zone": "ADH 1",
      "x": 9.0,
      "y": 7.5,
      "width": 9.5,
      "height": 2.2,
      "color": "#2B6CB0",
      "category": "ADH",
      "floor": "1F"
    },
    {
      "id": "eq_lift_north",
      "code": "Lift 1",
      "name": "貨梯 (北側貨梯)",
      "zone": "Utility",
      "x": 28.5,
      "y": 1.0,
      "width": 4.8,
      "height": 4.5,
      "color": "#718096",
      "category": "Utility",
      "floor": "1F"
    },
    {
      "id": "eq_compressor",
      "code": "ปั๊มลม",
      "name": "空壓機房 (Air Compressor)",
      "zone": "Utility",
      "x": 44.0,
      "y": -2.5,
      "width": 6.0,
      "height": 2.2,
      "color": "#4A5568",
      "category": "Utility",
      "floor": "1F"
    },
    {
      "id": "eq_foam_f1_1",
      "code": "F1-1",
      "name": "Foam (發泡線主機 F1-1)",
      "zone": "Foam/Latex",
      "x": 42.0,
      "y": 2.0,
      "width": 14.5,
      "height": 4.2,
      "color": "#319795",
      "category": "Foam",
      "floor": "1F"
    },
    {
      "id": "eq_eva1_a1_1",
      "code": "A1-1",
      "name": "EVA 1 (EVA 生產線 A1-1)",
      "zone": "EVA",
      "x": 64.5,
      "y": 2.0,
      "width": 18.0,
      "height": 4.5,
      "color": "#2C7A7B",
      "category": "EVA",
      "floor": "1F"
    },
    {
      "id": "eq_latex_h1_1",
      "code": "H1-1",
      "name": "Latex (乳膠加工機 H1-1)",
      "zone": "Foam/Latex",
      "x": 84.0,
      "y": 6.5,
      "width": 12.5,
      "height": 4.0,
      "color": "#319795",
      "category": "Latex",
      "floor": "1F"
    },
    {
      "id": "eq_adh2_m2_1",
      "code": "M2-1",
      "name": "ADH 2 (貼合機主機 M2-1)",
      "zone": "ADH 2",
      "x": 9.0,
      "y": 14.5,
      "width": 11.5,
      "height": 2.5,
      "color": "#2B6CB0",
      "category": "ADH",
      "floor": "1F"
    },
    {
      "id": "eq_qa2_q2_2",
      "code": "Q2-2",
      "name": "QA 2 (品管檢測站 2)",
      "zone": "ADH 2",
      "x": 23.5,
      "y": 19.5,
      "width": 2.8,
      "height": 2.2,
      "color": "#3182CE",
      "category": "QC",
      "floor": "1F"
    },
    {
      "id": "eq_qa1_q2_1",
      "code": "Q2-1",
      "name": "QA 1 (品管檢測站 1)",
      "zone": "ADH 2",
      "x": 23.5,
      "y": 22.5,
      "width": 2.8,
      "height": 2.2,
      "color": "#3182CE",
      "category": "QC",
      "floor": "1F"
    },
    {
      "id": "eq_qa3_q2_3",
      "code": "Q2-3",
      "name": "QA 3 (品管檢測站 3)",
      "zone": "ADH 2",
      "x": 10.5,
      "y": 24.5,
      "width": 2.2,
      "height": 4.8,
      "color": "#3182CE",
      "category": "QC",
      "floor": "1F"
    },
    {
      "id": "eq_lift_west",
      "code": "貨梯",
      "name": "貨梯 (西側重型貨梯)",
      "zone": "Utility",
      "x": 19.0,
      "y": 29.5,
      "width": 4.8,
      "height": 4.8,
      "color": "#718096",
      "category": "Utility",
      "floor": "1F"
    },
    {
      "id": "eq_stairs",
      "code": "連通道",
      "name": "連通道 / 樓梯間",
      "zone": "Utility",
      "x": 13.5,
      "y": 32.5,
      "width": 5.0,
      "height": 3.2,
      "color": "#48BB78",
      "category": "Utility",
      "floor": "1F"
    },
    {
      "id": "eq_office",
      "code": "Office",
      "name": "廠務辦公室 (Office)",
      "zone": "Office",
      "x": 35.5,
      "y": 28.5,
      "width": 11.5,
      "height": 10.5,
      "color": "#CBD5E0",
      "category": "Office",
      "floor": "1F"
    },
    {
      "id": "eq_af1_g2_1",
      "code": "G2-1",
      "name": "AF 1 (自動化設備 1)",
      "zone": "QC Line",
      "x": 51.0,
      "y": 14.5,
      "width": 2.4,
      "height": 5.5,
      "color": "#4A90E2",
      "category": "Automation",
      "floor": "1F"
    },
    {
      "id": "eq_af2_g2_2",
      "code": "G2-2",
      "name": "AF 2 (自動化設備 2)",
      "zone": "QC Line",
      "x": 44.5,
      "y": 22.5,
      "width": 4.8,
      "height": 3.8,
      "color": "#4A90E2",
      "category": "Automation",
      "floor": "1F"
    },
    {
      "id": "eq_qc4_b1_4",
      "code": "B1-4",
      "name": "QC 4 (品檢桌 4)",
      "zone": "QC Line",
      "x": 56.5,
      "y": 14.0,
      "width": 2.5,
      "height": 5.2,
      "color": "#63B3ED",
      "category": "QC",
      "floor": "1F"
    },
    {
      "id": "eq_qc3_b1_3",
      "code": "B1-3",
      "name": "QC 3 (品檢桌 3)",
      "zone": "QC Line",
      "x": 60.0,
      "y": 14.0,
      "width": 2.5,
      "height": 5.2,
      "color": "#63B3ED",
      "category": "QC",
      "floor": "1F"
    },
    {
      "id": "eq_qc2_b1_2",
      "code": "B1-2",
      "name": "QC 2 (品檢桌 2)",
      "zone": "QC Line",
      "x": 66.5,
      "y": 14.0,
      "width": 2.5,
      "height": 5.2,
      "color": "#63B3ED",
      "category": "QC",
      "floor": "1F"
    },
    {
      "id": "eq_qc1_b1_1",
      "code": "B1-1",
      "name": "QC 1 (品檢桌 1)",
      "zone": "QC Line",
      "x": 70.5,
      "y": 14.0,
      "width": 2.5,
      "height": 5.2,
      "color": "#63B3ED",
      "category": "QC",
      "floor": "1F"
    },
    {
      "id": "eq_eva3",
      "code": "EVA 3",
      "name": "EVA 3 (EVA 產線 3)",
      "zone": "EVA",
      "x": 78.5,
      "y": 15.0,
      "width": 11.0,
      "height": 7.5,
      "color": "#2C7A7B",
      "category": "EVA",
      "floor": "1F"
    },
    {
      "id": "eq_pf1_c1_1",
      "code": "C1-1",
      "name": "PF 1 (精密切斷機 1)",
      "zone": "Cutting",
      "x": 58.0,
      "y": 28.5,
      "width": 18.5,
      "height": 3.8,
      "color": "#D69E2E",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_autocut2_e1_2",
      "code": "E1-2",
      "name": "Auto Cut 2 (自動裁斷機 2)",
      "zone": "Cutting",
      "x": 81.0,
      "y": 29.5,
      "width": 5.0,
      "height": 2.2,
      "color": "#F5A623",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_autocut1_e1_1",
      "code": "E1-1",
      "name": "Auto Cut 1 (自動裁斷機 1)",
      "zone": "Cutting",
      "x": 81.0,
      "y": 35.0,
      "width": 5.0,
      "height": 2.2,
      "color": "#F5A623",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_vcut1_j1_2",
      "code": "J1-2",
      "name": "V Cut 1 (V型裁斷機 1)",
      "zone": "Cutting",
      "x": 75.0,
      "y": 34.0,
      "width": 4.5,
      "height": 4.5,
      "color": "#F5A623",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_pf2_c1_2",
      "code": "C1-2",
      "name": "PF 2 (精密切斷機 2)",
      "zone": "Cutting",
      "x": 66.0,
      "y": 34.0,
      "width": 7.5,
      "height": 3.5,
      "color": "#D69E2E",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_diecut_l4_1",
      "code": "L4-1",
      "name": "Die Cut (模切機 L4-1)",
      "zone": "Cutting",
      "x": 58.5,
      "y": 34.0,
      "width": 4.2,
      "height": 4.0,
      "color": "#ECC94B",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_vcut3_j1_3",
      "code": "J1-3",
      "name": "V Cut 3 (V型裁斷機 3)",
      "zone": "Cutting",
      "x": 59.5,
      "y": 39.5,
      "width": 4.5,
      "height": 4.5,
      "color": "#F5A623",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_diecut_sub",
      "code": "Die Cut",
      "name": "Die Cut (沖床模切機)",
      "zone": "Cutting",
      "x": 55.0,
      "y": 39.5,
      "width": 3.8,
      "height": 4.0,
      "color": "#ECC94B",
      "category": "Cutting",
      "floor": "1F"
    },
    {
      "id": "eq_eva2_a1_2",
      "code": "A1-2",
      "name": "EVA 2 (EVA 生產線 A1-2)",
      "zone": "EVA",
      "x": 65.5,
      "y": 39.5,
      "width": 18.0,
      "height": 3.5,
      "color": "#2C7A7B",
      "category": "EVA",
      "floor": "1F"
    },
    {
      "id": "eq_slice1_d1_1",
      "code": "D1-1",
      "name": "Slice 1 (分切機 D1-1)",
      "zone": "Slicing",
      "x": 90.5,
      "y": 42.0,
      "width": 4.5,
      "height": 9.5,
      "color": "#9F7AEA",
      "category": "Slicing",
      "floor": "1F"
    },
    {
      "id": "eq_welding",
      "code": "Welding",
      "name": "Welding (焊接工作站)",
      "zone": "Welding",
      "x": 95.5,
      "y": 42.0,
      "width": 4.5,
      "height": 9.5,
      "color": "#805AD5",
      "category": "Welding",
      "floor": "1F"
    },
    {
      "id": "eq_fdc_k1_1",
      "code": "K1-1",
      "name": "FDC 物料架 K1-1",
      "zone": "Storage",
      "x": 89.5,
      "y": 28.5,
      "width": 2.4,
      "height": 2.8,
      "color": "#38A169",
      "category": "Storage",
      "floor": "1F"
    },
    {
      "id": "eq_fdc_k1_2",
      "code": "K1-2",
      "name": "FDC 物料架 K1-2",
      "zone": "Storage",
      "x": 92.5,
      "y": 28.5,
      "width": 2.4,
      "height": 2.8,
      "color": "#38A169",
      "category": "Storage",
      "floor": "1F"
    },
    {
      "id": "eq_fdc_i1_1",
      "code": "I1-1",
      "name": "FDC 棧板區 I1-1",
      "zone": "Storage",
      "x": 92.0,
      "y": 32.0,
      "width": 2.4,
      "height": 2.8,
      "color": "#38A169",
      "category": "Storage",
      "floor": "1F"
    },
    {
      "id": "eq_fdc_i1_4",
      "code": "I1-4",
      "name": "FDC 棧板區 I1-4",
      "zone": "Storage",
      "x": 95.5,
      "y": 32.0,
      "width": 2.4,
      "height": 2.8,
      "color": "#38A169",
      "category": "Storage",
      "floor": "1F"
    },
    {
      "id": "eq_fdc_i1_5",
      "code": "I1-5",
      "name": "FDC 棧板區 I1-5",
      "zone": "Storage",
      "x": 95.5,
      "y": 28.5,
      "width": 2.4,
      "height": 2.8,
      "color": "#38A169",
      "category": "Storage",
      "floor": "1F"
    },
    {
      "id": "eq_cnc_room",
      "code": "CNC Room",
      "name": "CNC 精密加工區 (防塵隔間)",
      "zone": "CNC",
      "x": 81.0,
      "y": 55.5,
      "width": 19.5,
      "height": 11.5,
      "color": "#E2E8F0",
      "category": "CNC",
      "is_room": true,
      "floor": "1F"
    },
    {
      "id": "eq_cnc_p1_1",
      "code": "P1-1",
      "name": "CNC 機台 P1-1",
      "zone": "CNC",
      "x": 90.5,
      "y": 62.0,
      "width": 2.4,
      "height": 2.4,
      "color": "#4A5568",
      "category": "CNC",
      "floor": "1F"
    },
    {
      "id": "eq_cnc_p1_2",
      "code": "P1-2",
      "name": "CNC 機台 P1-2",
      "zone": "CNC",
      "x": 93.8,
      "y": 62.0,
      "width": 2.4,
      "height": 2.4,
      "color": "#4A5568",
      "category": "CNC",
      "floor": "1F"
    },
    {
      "id": "eq_cnc_p1_3",
      "code": "P1-3",
      "name": "CNC 機台 P1-3",
      "zone": "CNC",
      "x": 97.0,
      "y": 62.0,
      "width": 2.4,
      "height": 2.4,
      "color": "#4A5568",
      "category": "CNC",
      "floor": "1F"
    },
    {
      "id": "eq_cnc_p1_4",
      "code": "P1-4",
      "name": "CNC 機台 P1-4",
      "zone": "CNC",
      "x": 97.0,
      "y": 58.5,
      "width": 2.4,
      "height": 2.4,
      "color": "#4A5568",
      "category": "CNC",
      "floor": "1F"
    },
    {
      "id": "eq_cnc_p1_5",
      "code": "P1-5",
      "name": "CNC 機台 P1-5",
      "zone": "CNC",
      "x": 97.0,
      "y": 55.2,
      "width": 2.4,
      "height": 2.4,
      "color": "#4A5568",
      "category": "CNC",
      "floor": "1F"
    },
    {
      "id": "eq_guard",
      "code": "Guard",
      "name": "大門警衛室 (Guard Booth)",
      "zone": "Infrastructure",
      "x": -5.0,
      "y": 55.5,
      "width": 4.5,
      "height": 6.5,
      "color": "#ED64A6",
      "category": "Infrastructure",
      "floor": "1F"
    },
    {
      "id": "eq_gate",
      "code": "GATE",
      "name": "廠區正門出入口 (Main Gate)",
      "zone": "Infrastructure",
      "x": -5.5,
      "y": 42.0,
      "width": 5.0,
      "height": 12.0,
      "color": "#ED8936",
      "category": "Infrastructure",
      "floor": "1F"
    },
    {
      "id": "eq_pallet_1",
      "code": "PL-1",
      "name": "物料暫存棧板排 A",
      "zone": "Storage",
      "x": 42.0,
      "y": 46.5,
      "width": 11.5,
      "height": 3.0,
      "color": "#2F855A",
      "category": "Storage",
      "floor": "1F"
    },
    {
      "id": "eq_pallet_2",
      "code": "PL-2",
      "name": "物料暫存棧板排 B",
      "zone": "Storage",
      "x": 58.0,
      "y": 46.5,
      "width": 12.5,
      "height": 3.0,
      "color": "#2F855A",
      "category": "Storage",
      "floor": "1F"
    },
    {
      "id": "eq_pallet_3",
      "code": "PL-3",
      "name": "成品棧板出貨區 C",
      "zone": "Storage",
      "x": 73.0,
      "y": 46.5,
      "width": 8.0,
      "height": 3.0,
      "color": "#2F855A",
      "category": "Storage",
      "floor": "1F"
    }
  ],
  "walls": [
    {
      "x1": 0.0,
      "y1": 0.0,
      "x2": 100.0,
      "y2": 0.0,
      "thickness": 0.3,
      "type": "exterior"
    },
    {
      "x1": 100.0,
      "y1": 0.0,
      "x2": 100.0,
      "y2": 20.0,
      "thickness": 0.3,
      "type": "exterior"
    },
    {
      "x1": 100.0,
      "y1": 20.0,
      "x2": 90.0,
      "y2": 20.0,
      "thickness": 0.3,
      "type": "interior"
    },
    {
      "x1": 90.0,
      "y1": 20.0,
      "x2": 90.0,
      "y2": 40.0,
      "thickness": 0.3,
      "type": "interior"
    },
    {
      "x1": 90.0,
      "y1": 40.0,
      "x2": 100.0,
      "y2": 40.0,
      "thickness": 0.3,
      "type": "interior"
    },
    {
      "x1": 100.0,
      "y1": 40.0,
      "x2": 100.0,
      "y2": 67.0,
      "thickness": 0.3,
      "type": "exterior"
    },
    {
      "x1": 100.0,
      "y1": 67.0,
      "x2": 80.0,
      "y2": 67.0,
      "thickness": 0.3,
      "type": "exterior"
    },
    {
      "x1": 80.0,
      "y1": 67.0,
      "x2": 80.0,
      "y2": 55.0,
      "thickness": 0.3,
      "type": "interior"
    },
    {
      "x1": 80.0,
      "y1": 55.0,
      "x2": 0.0,
      "y2": 55.0,
      "thickness": 0.3,
      "type": "exterior"
    },
    {
      "x1": 0.0,
      "y1": 55.0,
      "x2": 0.0,
      "y2": 0.0,
      "thickness": 0.3,
      "type": "exterior"
    },
    {
      "x1": 35.0,
      "y1": 28.0,
      "x2": 47.0,
      "y2": 28.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 47.0,
      "y1": 28.0,
      "x2": 47.0,
      "y2": 39.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 47.0,
      "y1": 39.0,
      "x2": 35.0,
      "y2": 39.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 35.0,
      "y1": 39.0,
      "x2": 35.0,
      "y2": 28.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 0.0,
      "y1": 11.0,
      "x2": 28.0,
      "y2": 11.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 28.0,
      "y1": 0.0,
      "x2": 28.0,
      "y2": 11.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 35.0,
      "y1": 0.0,
      "x2": 35.0,
      "y2": 11.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 56.0,
      "y1": 0.0,
      "x2": 56.0,
      "y2": 11.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 50.0,
      "y1": 11.0,
      "x2": 50.0,
      "y2": 26.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 74.0,
      "y1": 11.0,
      "x2": 74.0,
      "y2": 26.0,
      "thickness": 0.2,
      "type": "interior"
    },
    {
      "x1": 54.0,
      "y1": 44.0,
      "x2": 89.0,
      "y2": 44.0,
      "thickness": 0.2,
      "type": "interior"
    }
  ],
  "aisles": [
    {
      "x": 0.0,
      "y": 42.0,
      "width": 80.0,
      "height": 3.5,
      "name": "中央主幹物流道 (Main Forklift Aisle)"
    },
    {
      "x": 48.0,
      "y": 11.0,
      "width": 3.0,
      "height": 31.0,
      "name": "南北向連通走道 (North-South Connector)"
    },
    {
      "x": 75.0,
      "y": 44.0,
      "width": 3.5,
      "height": 11.0,
      "name": "CNC 聯絡通道 (CNC Access Aisle)"
    }
  ],
  "mezzanine_2f": {
    "title": "二樓新建倉庫工程平面圖 (2F Warehouse Mezzanine)",
    "dwg_scale": "1:150",
    "elevation_1f": "+0.60M",
    "elevation_2f": "+4.40M",
    "clear_height": "3.80M",
    "grid_x": {
      "names": [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8"
      ],
      "coords": [
        0.0,
        5.0,
        10.0,
        15.0,
        20.0,
        25.0,
        30.0,
        35.0
      ],
      "bay_size": 5.0,
      "total_width": 35.0
    },
    "grid_y": {
      "names": [
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G"
      ],
      "coords": [
        0.0,
        4.75,
        9.5,
        14.25,
        19.0,
        23.75,
        28.5
      ],
      "bay_size": 4.75,
      "total_depth": 28.5
    },
    "zones": [
      {
        "id": "zone_existing",
        "name": "既有夾層 (Existing Mezzanine)",
        "thai_name": "พื้นที่ชั้นลอยเดิม",
        "elevation": "+4.40M",
        "x": 0.0,
        "y": 19.0,
        "width": 15.0,
        "height": 4.75,
        "area_sqm": 71.25,
        "pattern": "hatch_diagonal",
        "color": "#CBD5E0"
      },
      {
        "id": "zone_b",
        "name": "新建夾層 ZONE B (Mezzanine Zone B)",
        "thai_name": "ชั้นลอย ZONE B",
        "elevation": "+4.40M",
        "x": 0.0,
        "y": 9.5,
        "width": 15.0,
        "height": 9.5,
        "area_sqm": 142.5,
        "pattern": "steel_deck_grating",
        "color": "#4299E1"
      },
      {
        "id": "zone_a_north",
        "name": "新建夾層 ZONE A (北翼突起部)",
        "thai_name": "ชั้นลอย ZONE A",
        "elevation": "+4.40M",
        "x": 30.0,
        "y": 14.25,
        "width": 5.0,
        "height": 4.75,
        "area_sqm": 23.75,
        "pattern": "steel_deck_grating",
        "color": "#3182CE"
      },
      {
        "id": "zone_a_main",
        "name": "新建夾層 ZONE A (主倉儲區)",
        "thai_name": "ชั้นลอย ZONE A",
        "elevation": "+4.40M",
        "x": 20.0,
        "y": 19.0,
        "width": 15.0,
        "height": 9.5,
        "area_sqm": 142.5,
        "pattern": "steel_deck_grating",
        "color": "#3182CE"
      },
      {
        "id": "zone_connector",
        "name": "連通走廊與梯廳",
        "thai_name": "ทางเชื่อม",
        "elevation": "+4.40M",
        "x": 15.0,
        "y": 19.0,
        "width": 3.2,
        "height": 4.75,
        "area_sqm": 15.2,
        "pattern": "steel_deck_grating",
        "color": "#3182CE"
      }
    ],
    "handrails": [
      {
        "x1": 0.0,
        "y1": 9.5,
        "x2": 15.0,
        "y2": 9.5,
        "name": "Zone B 北側防護欄杆 (Hand Rail)"
      },
      {
        "x1": 15.0,
        "y1": 9.5,
        "x2": 15.0,
        "y2": 19.0,
        "name": "Zone B 東側防護欄杆 (Hand Rail)"
      },
      {
        "x1": 30.0,
        "y1": 14.25,
        "x2": 35.0,
        "y2": 14.25,
        "name": "Zone A 北側防護欄杆 (Hand Rail)"
      },
      {
        "x1": 30.0,
        "y1": 14.25,
        "x2": 30.0,
        "y2": 19.0,
        "name": "Zone A 西側防護欄杆 (Hand Rail)"
      },
      {
        "x1": 20.0,
        "y1": 19.0,
        "x2": 30.0,
        "y2": 19.0,
        "name": "Zone A 中段防護欄杆 (Hand Rail)"
      },
      {
        "x1": 15.0,
        "y1": 19.0,
        "x2": 16.8,
        "y2": 19.0,
        "name": "連通道北側欄杆 (Hand Rail)"
      },
      {
        "x1": 16.8,
        "y1": 21.2,
        "x2": 16.8,
        "y2": 23.75,
        "name": "貨梯南側防墜護欄 (Hand Rail)"
      },
      {
        "x1": 18.2,
        "y1": 19.0,
        "x2": 18.2,
        "y2": 23.75,
        "name": "樓梯側向防護欄杆 (Hand Rail)"
      }
    ],
    "vertical_circulation": {
      "lift": {
        "x": 16.8,
        "y": 19.0,
        "width": 1.4,
        "height": 2.2,
        "name": "貨梯 (LIFT EL. +0.60M ~ +4.40M)",
        "code": "LIFT"
      },
      "stair": {
        "x": 18.2,
        "y": 19.0,
        "width": 1.8,
        "height": 4.75,
        "name": "安全樓梯 STAIR ST-01 (DWG. NO. : S-05)",
        "code": "ST-01"
      },
      "ramp": {
        "x": 15.0,
        "y": 23.75,
        "width": 5.0,
        "height": 2.75,
        "name": "一樓大門出入口斜坡 (ENTRANCE & RAMP)",
        "code": "RAMP"
      }
    },
    "support_posts": [
      {
        "x": 5.0,
        "y": 9.5,
        "name": "立柱 C2"
      },
      {
        "x": 10.0,
        "y": 9.5,
        "name": "立柱 C3"
      },
      {
        "x": 15.0,
        "y": 9.5,
        "name": "立柱 C4"
      },
      {
        "x": 5.0,
        "y": 14.25,
        "name": "立柱 D2"
      },
      {
        "x": 10.0,
        "y": 14.25,
        "name": "立柱 D3"
      },
      {
        "x": 15.0,
        "y": 14.25,
        "name": "立柱 D4"
      }
    ]
  },
  "equipment_2f": [
    {
      "id": "eq2f_rk_b1",
      "code": "RK-B1",
      "name": "重型鋼製物料架 B1",
      "zone": "Zone B 倉庫",
      "floor": "2F",
      "x": 1.5,
      "y": 10.5,
      "width": 5.5,
      "height": 1.8,
      "rotation": 0,
      "color": "#3182CE",
      "category": "2F Storage"
    },
    {
      "id": "eq2f_rk_b2",
      "code": "RK-B2",
      "name": "重型鋼製物料架 B2",
      "zone": "Zone B 倉庫",
      "floor": "2F",
      "x": 8.5,
      "y": 10.5,
      "width": 5.5,
      "height": 1.8,
      "rotation": 0,
      "color": "#3182CE",
      "category": "2F Storage"
    },
    {
      "id": "eq2f_rk_b3",
      "code": "RK-B3",
      "name": "重型鋼製物料架 B3",
      "zone": "Zone B 倉庫",
      "floor": "2F",
      "x": 1.5,
      "y": 14.5,
      "width": 5.5,
      "height": 1.8,
      "rotation": 0,
      "color": "#3182CE",
      "category": "2F Storage"
    },
    {
      "id": "eq2f_rk_b4",
      "code": "RK-B4",
      "name": "重型鋼製物料架 B4",
      "zone": "Zone B 倉庫",
      "floor": "2F",
      "x": 8.5,
      "y": 14.5,
      "width": 5.5,
      "height": 1.8,
      "rotation": 0,
      "color": "#3182CE",
      "category": "2F Storage"
    },
    {
      "id": "eq2f_pl_a1",
      "code": "PL-A1",
      "name": "棧板儲存排 A1",
      "zone": "Zone A 倉庫",
      "floor": "2F",
      "x": 21.0,
      "y": 20.5,
      "width": 6.0,
      "height": 2.4,
      "rotation": 0,
      "color": "#2F855A",
      "category": "2F Pallets"
    },
    {
      "id": "eq2f_pl_a2",
      "code": "PL-A2",
      "name": "棧板儲存排 A2",
      "zone": "Zone A 倉庫",
      "floor": "2F",
      "x": 28.0,
      "y": 20.5,
      "width": 6.0,
      "height": 2.4,
      "rotation": 0,
      "color": "#2F855A",
      "category": "2F Pallets"
    },
    {
      "id": "eq2f_pl_a3",
      "code": "PL-A3",
      "name": "棧板儲存排 A3",
      "zone": "Zone A 倉庫",
      "floor": "2F",
      "x": 21.0,
      "y": 24.5,
      "width": 6.0,
      "height": 2.4,
      "rotation": 0,
      "color": "#2F855A",
      "category": "2F Pallets"
    },
    {
      "id": "eq2f_pl_a4",
      "code": "PL-A4",
      "name": "棧板儲存排 A4",
      "zone": "Zone A 倉庫",
      "floor": "2F",
      "x": 28.0,
      "y": 24.5,
      "width": 6.0,
      "height": 2.4,
      "rotation": 0,
      "color": "#2F855A",
      "category": "2F Pallets"
    },
    {
      "id": "eq2f_ex_1",
      "code": "EX-1",
      "name": "既有夾層物料排 1",
      "zone": "既有夾層",
      "floor": "2F",
      "x": 2.0,
      "y": 20.0,
      "width": 5.0,
      "height": 2.5,
      "rotation": 0,
      "color": "#718096",
      "category": "2F Existing"
    },
    {
      "id": "eq2f_ex_2",
      "code": "EX-2",
      "name": "既有夾層物料排 2",
      "zone": "既有夾層",
      "floor": "2F",
      "x": 8.5,
      "y": 20.0,
      "width": 5.0,
      "height": 2.5,
      "rotation": 0,
      "color": "#718096",
      "category": "2F Existing"
    },
    {
      "id": "eq2f_staging",
      "code": "STG-2F",
      "name": "貨梯前置緩衝進出貨區",
      "zone": "垂直梯廳",
      "floor": "2F",
      "x": 15.2,
      "y": 20.0,
      "width": 2.8,
      "height": 2.8,
      "rotation": 0,
      "color": "#DD6B20",
      "category": "2F Staging"
    }
  ]
};
